// Inlined JSON-LD context — same terms as vocab/aleph-context.jsonld, embedded
// so SHACL validation never has to dereference the relative ./context.jsonld.
export const INLINE_CONTEXT: Record<string, unknown> = {
  aleph: 'https://vocab.aleph.wiki/',
  prov: 'http://www.w3.org/ns/prov#',
  skos: 'http://www.w3.org/2004/02/skos/core#',
  rdfs: 'http://www.w3.org/2000/01/rdf-schema#',
  xsd: 'http://www.w3.org/2001/XMLSchema#',
  foaf: 'http://xmlns.com/foaf/0.1/',
  g: 'https://aleph.wiki/g/',
  ChatMessage: 'aleph:ChatMessage',
  Concept: 'aleph:Concept',
  Edit: 'aleph:Edit',
  WebSearchAssertion: 'aleph:WebSearchAssertion',
  SparqlAssertion: 'aleph:SparqlAssertion',
  ImaginedAssertion: 'aleph:ImaginedAssertion',
  position: { '@id': 'aleph:position', '@type': 'xsd:integer' },
  speaker: { '@id': 'aleph:speaker' },
  body: { '@id': 'aleph:body' },
  editKind: { '@id': 'aleph:editKind' },
  derivedFrom: { '@id': 'aleph:derivedFrom', '@type': '@id' },
  searchQuery: { '@id': 'aleph:searchQuery' },
  query: { '@id': 'aleph:query' },
  endpoints: { '@id': 'aleph:endpoints' },
  prefLabel: { '@id': 'skos:prefLabel', '@container': '@language' },
  broader: { '@id': 'skos:broader', '@type': '@id' },
  related: { '@id': 'skos:related', '@type': '@id' },
  wasGeneratedBy: { '@id': 'prov:wasGeneratedBy', '@type': '@id' },
  generatedAtTime: { '@id': 'prov:generatedAtTime', '@type': 'xsd:dateTime' },
};
